# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from localvoice.v1 import localvoice_pb2 as localvoice_dot_v1_dot_localvoice__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in localvoice/v1/localvoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalVoiceStub(object):
    """LocalVoice service for local TTS inference via gRPC over Unix Domain Socket.

    This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
    and consumed by Go provider clients in omni-f5tts, omni-qwen, etc.

    Connection: unix:///tmp/omnivoice-{provider}.sock
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
                '/omnivoice.localvoice.v1.LocalVoice/Synthesize',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.SynthesizeWithReference = channel.unary_stream(
                '/omnivoice.localvoice.v1.LocalVoice/SynthesizeWithReference',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.ReferenceSynthesizeRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.PrepareVoiceProfile = channel.unary_unary(
                '/omnivoice.localvoice.v1.LocalVoice/PrepareVoiceProfile',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/omnivoice.localvoice.v1.LocalVoice/Health',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.HealthRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/omnivoice.localvoice.v1.LocalVoice/LoadModel',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/omnivoice.localvoice.v1.LocalVoice/UnloadModel',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.RuntimeInfo = channel.unary_unary(
                '/omnivoice.localvoice.v1.LocalVoice/RuntimeInfo',
                request_serializer=localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoRequest.SerializeToString,
                response_deserializer=localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoResponse.FromString,
                _registered_method=True)


class LocalVoiceServicer(object):
    """LocalVoice service for local TTS inference via gRPC over Unix Domain Socket.

    This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
    and consumed by Go provider clients in omni-f5tts, omni-qwen, etc.

    Connection: unix:///tmp/omnivoice-{provider}.sock
    """

    def Synthesize(self, request, context):
        """Synthesize converts text to speech, streaming audio chunks as they generate.
        This enables low-latency playback before synthesis completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeWithReference(self, request, context):
        """SynthesizeWithReference performs zero-shot voice cloning using reference audio.
        The reference audio and transcript are used to clone the voice characteristics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareVoiceProfile(self, request, context):
        """PrepareVoiceProfile pre-computes and caches a voice embedding from reference audio.
        Subsequent synthesis with this profile ID will be faster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health returns the health status and model information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """LoadModel loads the TTS model into memory.
        Call this before Synthesize if the model is not auto-loaded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """UnloadModel unloads the model from memory to free resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RuntimeInfo(self, request, context):
        """RuntimeInfo returns information about the runtime environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalVoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.SynthesizeRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.SerializeToString,
            ),
            'SynthesizeWithReference': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeWithReference,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.ReferenceSynthesizeRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.SerializeToString,
            ),
            'PrepareVoiceProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareVoiceProfile,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.HealthRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.HealthResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.LoadModelRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.UnloadModelRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.UnloadModelResponse.SerializeToString,
            ),
            'RuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.RuntimeInfo,
                    request_deserializer=localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoRequest.FromString,
                    response_serializer=localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnivoice.localvoice.v1.LocalVoice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omnivoice.localvoice.v1.LocalVoice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalVoice(object):
    """LocalVoice service for local TTS inference via gRPC over Unix Domain Socket.

    This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
    and consumed by Go provider clients in omni-f5tts, omni-qwen, etc.

    Connection: unix:///tmp/omnivoice-{provider}.sock
    """

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/Synthesize',
            localvoice_dot_v1_dot_localvoice__pb2.SynthesizeRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeWithReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/SynthesizeWithReference',
            localvoice_dot_v1_dot_localvoice__pb2.ReferenceSynthesizeRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareVoiceProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/PrepareVoiceProfile',
            localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.PrepareVoiceProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/Health',
            localvoice_dot_v1_dot_localvoice__pb2.HealthRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/LoadModel',
            localvoice_dot_v1_dot_localvoice__pb2.LoadModelRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/UnloadModel',
            localvoice_dot_v1_dot_localvoice__pb2.UnloadModelRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.localvoice.v1.LocalVoice/RuntimeInfo',
            localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoRequest.SerializeToString,
            localvoice_dot_v1_dot_localvoice__pb2.RuntimeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
