// Copyright 2024 PlexusOne. All rights reserved.
// Use of this source code is governed by the MIT license.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: localstt/v1/localstt.proto

package localsttv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType identifies the type of stream event.
type EventType int32

const (
	// EVENT_TYPE_UNSPECIFIED is the default value.
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// EVENT_TYPE_TRANSCRIPT is a transcription result (partial or final).
	EventType_EVENT_TYPE_TRANSCRIPT EventType = 1
	// EVENT_TYPE_SPEECH_START indicates the user started speaking.
	EventType_EVENT_TYPE_SPEECH_START EventType = 2
	// EVENT_TYPE_SPEECH_END indicates the user stopped speaking.
	EventType_EVENT_TYPE_SPEECH_END EventType = 3
	// EVENT_TYPE_ERROR indicates an error occurred.
	EventType_EVENT_TYPE_ERROR EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_TRANSCRIPT",
		2: "EVENT_TYPE_SPEECH_START",
		3: "EVENT_TYPE_SPEECH_END",
		4: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":  0,
		"EVENT_TYPE_TRANSCRIPT":   1,
		"EVENT_TYPE_SPEECH_START": 2,
		"EVENT_TYPE_SPEECH_END":   3,
		"EVENT_TYPE_ERROR":        4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_localstt_v1_localstt_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_localstt_v1_localstt_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{0}
}

// TranscribeRequest is a request to transcribe audio.
type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// audio is the audio data to transcribe.
	Audio []byte `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	// config contains transcription configuration.
	Config        *TranscriptionConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TranscribeRequest) GetConfig() *TranscriptionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// TranscriptionConfig configures a transcription request.
type TranscriptionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// language is the BCP-47 language code (e.g., "en", "zh").
	// Leave empty for automatic detection.
	Language *string `protobuf:"bytes,1,opt,name=language,proto3,oneof" json:"language,omitempty"`
	// model is the model variant to use (e.g., "tiny", "base", "small", "medium", "large", "turbo").
	Model *string `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// enable_word_timestamps includes word-level timestamps.
	EnableWordTimestamps bool `protobuf:"varint,3,opt,name=enable_word_timestamps,json=enableWordTimestamps,proto3" json:"enable_word_timestamps,omitempty"`
	// enable_punctuation adds punctuation to transcription.
	EnablePunctuation bool `protobuf:"varint,4,opt,name=enable_punctuation,json=enablePunctuation,proto3" json:"enable_punctuation,omitempty"`
	// task is "transcribe" (default) or "translate" (to English).
	Task *string `protobuf:"bytes,5,opt,name=task,proto3,oneof" json:"task,omitempty"`
	// initial_prompt is optional text to condition the model.
	InitialPrompt *string `protobuf:"bytes,6,opt,name=initial_prompt,json=initialPrompt,proto3,oneof" json:"initial_prompt,omitempty"`
	// input_format describes the audio format.
	InputFormat   *AudioFormat `protobuf:"bytes,7,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionConfig) Reset() {
	*x = TranscriptionConfig{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionConfig) ProtoMessage() {}

func (x *TranscriptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionConfig.ProtoReflect.Descriptor instead.
func (*TranscriptionConfig) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptionConfig) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *TranscriptionConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *TranscriptionConfig) GetEnableWordTimestamps() bool {
	if x != nil {
		return x.EnableWordTimestamps
	}
	return false
}

func (x *TranscriptionConfig) GetEnablePunctuation() bool {
	if x != nil {
		return x.EnablePunctuation
	}
	return false
}

func (x *TranscriptionConfig) GetTask() string {
	if x != nil && x.Task != nil {
		return *x.Task
	}
	return ""
}

func (x *TranscriptionConfig) GetInitialPrompt() string {
	if x != nil && x.InitialPrompt != nil {
		return *x.InitialPrompt
	}
	return ""
}

func (x *TranscriptionConfig) GetInputFormat() *AudioFormat {
	if x != nil {
		return x.InputFormat
	}
	return nil
}

// AudioFormat describes the audio encoding.
type AudioFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encoding is the audio encoding ("wav", "mp3", "flac", "pcm_s16le", "pcm_f32le").
	Encoding string `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// sample_rate is the sample rate in Hz (e.g., 16000, 44100).
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// channels is the number of audio channels (1 = mono, 2 = stereo).
	Channels      int32 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFormat) Reset() {
	*x = AudioFormat{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFormat) ProtoMessage() {}

func (x *AudioFormat) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFormat.ProtoReflect.Descriptor instead.
func (*AudioFormat) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{2}
}

func (x *AudioFormat) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *AudioFormat) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioFormat) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// TranscribeResponse contains the transcription result.
type TranscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the full transcription text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// segments contains segment-level details.
	Segments []*Segment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	// language is the detected language.
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	// language_confidence is the confidence in language detection (0.0 to 1.0).
	LanguageConfidence float32 `protobuf:"fixed32,4,opt,name=language_confidence,json=languageConfidence,proto3" json:"language_confidence,omitempty"`
	// duration_ms is the audio duration in milliseconds.
	DurationMs int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// processing_time_ms is the time taken to transcribe in milliseconds.
	ProcessingTimeMs int64 `protobuf:"varint,6,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *TranscribeResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeResponse) GetLanguageConfidence() float32 {
	if x != nil {
		return x.LanguageConfidence
	}
	return 0
}

func (x *TranscribeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TranscribeResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Segment represents a segment of transcription.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the segment identifier.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// text is the transcribed text for this segment.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// start_ms is when the segment starts in milliseconds.
	StartMs int64 `protobuf:"varint,3,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	// end_ms is when the segment ends in milliseconds.
	EndMs int64 `protobuf:"varint,4,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	// confidence is the average confidence for this segment (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// words contains word-level details (if enabled).
	Words         []*Word `protobuf:"bytes,6,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{4}
}

func (x *Segment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Segment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Segment) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *Segment) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *Segment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Segment) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

// Word represents a single transcribed word with timing.
type Word struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the transcribed word.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// start_ms is when the word starts in milliseconds.
	StartMs int64 `protobuf:"varint,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	// end_ms is when the word ends in milliseconds.
	EndMs int64 `protobuf:"varint,3,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	// confidence is the recognition confidence (0.0 to 1.0).
	Confidence    float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{5}
}

func (x *Word) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Word) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *Word) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *Word) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// AudioChunk represents a chunk of audio for streaming input.
type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains raw audio bytes.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// is_final is true for the last chunk.
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// config is included only on the first chunk.
	Config        *TranscriptionConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{6}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *AudioChunk) GetConfig() *TranscriptionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// TranscriptEvent represents a streaming transcription event.
type TranscriptEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the event type.
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=omnivoice.localstt.v1.EventType" json:"type,omitempty"`
	// transcript is the current transcript (partial or final).
	Transcript string `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`
	// is_final indicates if this is a final (non-interim) result.
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// segment contains segment details for final results.
	Segment *Segment `protobuf:"bytes,4,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
	// error contains error details if type is EVENT_TYPE_ERROR.
	Error         *string `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{7}
}

func (x *TranscriptEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *TranscriptEvent) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *TranscriptEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptEvent) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

func (x *TranscriptEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// HealthRequest is an empty request for health checking.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{8}
}

// HealthResponse contains health and model status information.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy indicates whether the service is operational.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// model_loaded indicates whether the STT model is loaded in memory.
	ModelLoaded bool `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	// model_name is the name of the loaded model (e.g., "whisper-large-v3-turbo").
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// model_version is the version of the loaded model.
	ModelVersion string `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// supported_languages lists the supported language codes.
	SupportedLanguages []string `protobuf:"bytes,5,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

// LoadModelRequest requests loading the STT model into memory.
type LoadModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model is the model variant to load (e.g., "tiny", "large-v3-turbo").
	Model *string `protobuf:"bytes,1,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// model_path optionally overrides the default model path.
	ModelPath     *string `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3,oneof" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{10}
}

func (x *LoadModelRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil && x.ModelPath != nil {
		return *x.ModelPath
	}
	return ""
}

// LoadModelResponse contains the result of model loading.
type LoadModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the model was loaded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// load_time_ms is the time taken to load the model in milliseconds.
	LoadTimeMs int64 `protobuf:"varint,2,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	// memory_used_mb is the memory consumed by the loaded model.
	MemoryUsedMb int64 `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	// model_name is the name of the loaded model.
	ModelName string `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// error_message contains error details if success is false.
	ErrorMessage  *string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{11}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetLoadTimeMs() int64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

func (x *LoadModelResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *LoadModelResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *LoadModelResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// UnloadModelRequest requests unloading the STT model from memory.
type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{12}
}

// UnloadModelResponse contains the result of model unloading.
type UnloadModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the model was unloaded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// memory_freed_mb is the memory freed by unloading.
	MemoryFreedMb int64 `protobuf:"varint,2,opt,name=memory_freed_mb,json=memoryFreedMb,proto3" json:"memory_freed_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{13}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadModelResponse) GetMemoryFreedMb() int64 {
	if x != nil {
		return x.MemoryFreedMb
	}
	return 0
}

// RuntimeInfoRequest requests runtime environment information.
type RuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoRequest) Reset() {
	*x = RuntimeInfoRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoRequest) ProtoMessage() {}

func (x *RuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*RuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{14}
}

// RuntimeInfoResponse contains runtime environment details.
type RuntimeInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_type is the compute device ("mlx", "mps", "cpu", "cuda").
	DeviceType string `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// memory_used_mb is the current memory usage in MB.
	MemoryUsedMb int64 `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	// memory_available_mb is the available memory in MB.
	MemoryAvailableMb int64 `protobuf:"varint,3,opt,name=memory_available_mb,json=memoryAvailableMb,proto3" json:"memory_available_mb,omitempty"`
	// framework_version is the ML framework version (e.g., MLX version).
	FrameworkVersion string `protobuf:"bytes,4,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	// python_version is the Python version if applicable.
	PythonVersion string `protobuf:"bytes,5,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	// model_info contains information about the loaded model.
	ModelInfo     *ModelInfo `protobuf:"bytes,6,opt,name=model_info,json=modelInfo,proto3,oneof" json:"model_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoResponse) Reset() {
	*x = RuntimeInfoResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoResponse) ProtoMessage() {}

func (x *RuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*RuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{15}
}

func (x *RuntimeInfoResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *RuntimeInfoResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *RuntimeInfoResponse) GetMemoryAvailableMb() int64 {
	if x != nil {
		return x.MemoryAvailableMb
	}
	return 0
}

func (x *RuntimeInfoResponse) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *RuntimeInfoResponse) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *RuntimeInfoResponse) GetModelInfo() *ModelInfo {
	if x != nil {
		return x.ModelInfo
	}
	return nil
}

// ModelInfo contains details about a loaded model.
type ModelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the model name (e.g., "whisper-large-v3-turbo").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// variant is the model variant (e.g., "mlx-q8").
	Variant string `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	// parameter_count is the number of model parameters.
	ParameterCount int64 `protobuf:"varint,3,opt,name=parameter_count,json=parameterCount,proto3" json:"parameter_count,omitempty"`
	// supported_languages lists the supported language codes.
	SupportedLanguages []string `protobuf:"bytes,4,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{16}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *ModelInfo) GetParameterCount() int64 {
	if x != nil {
		return x.ParameterCount
	}
	return 0
}

func (x *ModelInfo) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

// ListModelsRequest requests available models.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{17}
}

// ListModelsResponse contains available models.
type ListModelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// models lists available model variants.
	Models        []*AvailableModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{18}
}

func (x *ListModelsResponse) GetModels() []*AvailableModel {
	if x != nil {
		return x.Models
	}
	return nil
}

// AvailableModel describes an available model.
type AvailableModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the model name (e.g., "whisper-tiny", "whisper-large-v3-turbo").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description is a human-readable description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// size_mb is the model size in megabytes.
	SizeMb int64 `protobuf:"varint,3,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"`
	// is_downloaded indicates whether the model is locally cached.
	IsDownloaded  bool `protobuf:"varint,4,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableModel) Reset() {
	*x = AvailableModel{}
	mi := &file_localstt_v1_localstt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableModel) ProtoMessage() {}

func (x *AvailableModel) ProtoReflect() protoreflect.Message {
	mi := &file_localstt_v1_localstt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableModel.ProtoReflect.Descriptor instead.
func (*AvailableModel) Descriptor() ([]byte, []int) {
	return file_localstt_v1_localstt_proto_rawDescGZIP(), []int{19}
}

func (x *AvailableModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailableModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AvailableModel) GetSizeMb() int64 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

func (x *AvailableModel) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

var File_localstt_v1_localstt_proto protoreflect.FileDescriptor

const file_localstt_v1_localstt_proto_rawDesc = "" +
	"\n" +
	"\x1alocalstt/v1/localstt.proto\x12\x15omnivoice.localstt.v1\"m\n" +
	"\x11TranscribeRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12B\n" +
	"\x06config\x18\x02 \x01(\v2*.omnivoice.localstt.v1.TranscriptionConfigR\x06config\"\xf5\x02\n" +
	"\x13TranscriptionConfig\x12\x1f\n" +
	"\blanguage\x18\x01 \x01(\tH\x00R\blanguage\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x124\n" +
	"\x16enable_word_timestamps\x18\x03 \x01(\bR\x14enableWordTimestamps\x12-\n" +
	"\x12enable_punctuation\x18\x04 \x01(\bR\x11enablePunctuation\x12\x17\n" +
	"\x04task\x18\x05 \x01(\tH\x02R\x04task\x88\x01\x01\x12*\n" +
	"\x0einitial_prompt\x18\x06 \x01(\tH\x03R\rinitialPrompt\x88\x01\x01\x12E\n" +
	"\finput_format\x18\a \x01(\v2\".omnivoice.localstt.v1.AudioFormatR\vinputFormatB\v\n" +
	"\t_languageB\b\n" +
	"\x06_modelB\a\n" +
	"\x05_taskB\x11\n" +
	"\x0f_initial_prompt\"f\n" +
	"\vAudioFormat\x12\x1a\n" +
	"\bencoding\x18\x01 \x01(\tR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\"\x80\x02\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12:\n" +
	"\bsegments\x18\x02 \x03(\v2\x1e.omnivoice.localstt.v1.SegmentR\bsegments\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12/\n" +
	"\x13language_confidence\x18\x04 \x01(\x02R\x12languageConfidence\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12,\n" +
	"\x12processing_time_ms\x18\x06 \x01(\x03R\x10processingTimeMs\"\xb2\x01\n" +
	"\aSegment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bstart_ms\x18\x03 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x04 \x01(\x03R\x05endMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x121\n" +
	"\x05words\x18\x06 \x03(\v2\x1b.omnivoice.localstt.v1.WordR\x05words\"l\n" +
	"\x04Word\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bstart_ms\x18\x02 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x03 \x01(\x03R\x05endMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\x8f\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12G\n" +
	"\x06config\x18\x03 \x01(\v2*.omnivoice.localstt.v1.TranscriptionConfigH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\"\xf2\x01\n" +
	"\x0fTranscriptEvent\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .omnivoice.localstt.v1.EventTypeR\x04type\x12\x1e\n" +
	"\n" +
	"transcript\x18\x02 \x01(\tR\n" +
	"transcript\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12=\n" +
	"\asegment\x18\x04 \x01(\v2\x1e.omnivoice.localstt.v1.SegmentH\x00R\asegment\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_segmentB\b\n" +
	"\x06_error\"\x0f\n" +
	"\rHealthRequest\"\xc2\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12/\n" +
	"\x13supported_languages\x18\x05 \x03(\tR\x12supportedLanguages\"j\n" +
	"\x10LoadModelRequest\x12\x19\n" +
	"\x05model\x18\x01 \x01(\tH\x00R\x05model\x88\x01\x01\x12\"\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tH\x01R\tmodelPath\x88\x01\x01B\b\n" +
	"\x06_modelB\r\n" +
	"\v_model_path\"\xd0\x01\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\fload_time_ms\x18\x02 \x01(\x03R\n" +
	"loadTimeMs\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x03R\fmemoryUsedMb\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\x14\n" +
	"\x12UnloadModelRequest\"W\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fmemory_freed_mb\x18\x02 \x01(\x03R\rmemoryFreedMb\"\x14\n" +
	"\x12RuntimeInfoRequest\"\xb5\x02\n" +
	"\x13RuntimeInfoResponse\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12.\n" +
	"\x13memory_available_mb\x18\x03 \x01(\x03R\x11memoryAvailableMb\x12+\n" +
	"\x11framework_version\x18\x04 \x01(\tR\x10frameworkVersion\x12%\n" +
	"\x0epython_version\x18\x05 \x01(\tR\rpythonVersion\x12D\n" +
	"\n" +
	"model_info\x18\x06 \x01(\v2 .omnivoice.localstt.v1.ModelInfoH\x00R\tmodelInfo\x88\x01\x01B\r\n" +
	"\v_model_info\"\x93\x01\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\x12'\n" +
	"\x0fparameter_count\x18\x03 \x01(\x03R\x0eparameterCount\x12/\n" +
	"\x13supported_languages\x18\x04 \x03(\tR\x12supportedLanguages\"\x13\n" +
	"\x11ListModelsRequest\"S\n" +
	"\x12ListModelsResponse\x12=\n" +
	"\x06models\x18\x01 \x03(\v2%.omnivoice.localstt.v1.AvailableModelR\x06models\"\x84\x01\n" +
	"\x0eAvailableModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\asize_mb\x18\x03 \x01(\x03R\x06sizeMb\x12#\n" +
	"\ris_downloaded\x18\x04 \x01(\bR\fisDownloaded*\x90\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_TRANSCRIPT\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_SPEECH_START\x10\x02\x12\x19\n" +
	"\x15EVENT_TYPE_SPEECH_END\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x042\xb6\x05\n" +
	"\bLocalSTT\x12a\n" +
	"\n" +
	"Transcribe\x12(.omnivoice.localstt.v1.TranscribeRequest\x1a).omnivoice.localstt.v1.TranscribeResponse\x12a\n" +
	"\x10TranscribeStream\x12!.omnivoice.localstt.v1.AudioChunk\x1a&.omnivoice.localstt.v1.TranscriptEvent(\x010\x01\x12U\n" +
	"\x06Health\x12$.omnivoice.localstt.v1.HealthRequest\x1a%.omnivoice.localstt.v1.HealthResponse\x12^\n" +
	"\tLoadModel\x12'.omnivoice.localstt.v1.LoadModelRequest\x1a(.omnivoice.localstt.v1.LoadModelResponse\x12d\n" +
	"\vUnloadModel\x12).omnivoice.localstt.v1.UnloadModelRequest\x1a*.omnivoice.localstt.v1.UnloadModelResponse\x12d\n" +
	"\vRuntimeInfo\x12).omnivoice.localstt.v1.RuntimeInfoRequest\x1a*.omnivoice.localstt.v1.RuntimeInfoResponse\x12a\n" +
	"\n" +
	"ListModels\x12(.omnivoice.localstt.v1.ListModelsRequest\x1a).omnivoice.localstt.v1.ListModelsResponseBBZ@github.com/plexusone/omnivoice-core/proto/localstt/v1;localsttv1b\x06proto3"

var (
	file_localstt_v1_localstt_proto_rawDescOnce sync.Once
	file_localstt_v1_localstt_proto_rawDescData []byte
)

func file_localstt_v1_localstt_proto_rawDescGZIP() []byte {
	file_localstt_v1_localstt_proto_rawDescOnce.Do(func() {
		file_localstt_v1_localstt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localstt_v1_localstt_proto_rawDesc), len(file_localstt_v1_localstt_proto_rawDesc)))
	})
	return file_localstt_v1_localstt_proto_rawDescData
}

var file_localstt_v1_localstt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_localstt_v1_localstt_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_localstt_v1_localstt_proto_goTypes = []any{
	(EventType)(0),              // 0: omnivoice.localstt.v1.EventType
	(*TranscribeRequest)(nil),   // 1: omnivoice.localstt.v1.TranscribeRequest
	(*TranscriptionConfig)(nil), // 2: omnivoice.localstt.v1.TranscriptionConfig
	(*AudioFormat)(nil),         // 3: omnivoice.localstt.v1.AudioFormat
	(*TranscribeResponse)(nil),  // 4: omnivoice.localstt.v1.TranscribeResponse
	(*Segment)(nil),             // 5: omnivoice.localstt.v1.Segment
	(*Word)(nil),                // 6: omnivoice.localstt.v1.Word
	(*AudioChunk)(nil),          // 7: omnivoice.localstt.v1.AudioChunk
	(*TranscriptEvent)(nil),     // 8: omnivoice.localstt.v1.TranscriptEvent
	(*HealthRequest)(nil),       // 9: omnivoice.localstt.v1.HealthRequest
	(*HealthResponse)(nil),      // 10: omnivoice.localstt.v1.HealthResponse
	(*LoadModelRequest)(nil),    // 11: omnivoice.localstt.v1.LoadModelRequest
	(*LoadModelResponse)(nil),   // 12: omnivoice.localstt.v1.LoadModelResponse
	(*UnloadModelRequest)(nil),  // 13: omnivoice.localstt.v1.UnloadModelRequest
	(*UnloadModelResponse)(nil), // 14: omnivoice.localstt.v1.UnloadModelResponse
	(*RuntimeInfoRequest)(nil),  // 15: omnivoice.localstt.v1.RuntimeInfoRequest
	(*RuntimeInfoResponse)(nil), // 16: omnivoice.localstt.v1.RuntimeInfoResponse
	(*ModelInfo)(nil),           // 17: omnivoice.localstt.v1.ModelInfo
	(*ListModelsRequest)(nil),   // 18: omnivoice.localstt.v1.ListModelsRequest
	(*ListModelsResponse)(nil),  // 19: omnivoice.localstt.v1.ListModelsResponse
	(*AvailableModel)(nil),      // 20: omnivoice.localstt.v1.AvailableModel
}
var file_localstt_v1_localstt_proto_depIdxs = []int32{
	2,  // 0: omnivoice.localstt.v1.TranscribeRequest.config:type_name -> omnivoice.localstt.v1.TranscriptionConfig
	3,  // 1: omnivoice.localstt.v1.TranscriptionConfig.input_format:type_name -> omnivoice.localstt.v1.AudioFormat
	5,  // 2: omnivoice.localstt.v1.TranscribeResponse.segments:type_name -> omnivoice.localstt.v1.Segment
	6,  // 3: omnivoice.localstt.v1.Segment.words:type_name -> omnivoice.localstt.v1.Word
	2,  // 4: omnivoice.localstt.v1.AudioChunk.config:type_name -> omnivoice.localstt.v1.TranscriptionConfig
	0,  // 5: omnivoice.localstt.v1.TranscriptEvent.type:type_name -> omnivoice.localstt.v1.EventType
	5,  // 6: omnivoice.localstt.v1.TranscriptEvent.segment:type_name -> omnivoice.localstt.v1.Segment
	17, // 7: omnivoice.localstt.v1.RuntimeInfoResponse.model_info:type_name -> omnivoice.localstt.v1.ModelInfo
	20, // 8: omnivoice.localstt.v1.ListModelsResponse.models:type_name -> omnivoice.localstt.v1.AvailableModel
	1,  // 9: omnivoice.localstt.v1.LocalSTT.Transcribe:input_type -> omnivoice.localstt.v1.TranscribeRequest
	7,  // 10: omnivoice.localstt.v1.LocalSTT.TranscribeStream:input_type -> omnivoice.localstt.v1.AudioChunk
	9,  // 11: omnivoice.localstt.v1.LocalSTT.Health:input_type -> omnivoice.localstt.v1.HealthRequest
	11, // 12: omnivoice.localstt.v1.LocalSTT.LoadModel:input_type -> omnivoice.localstt.v1.LoadModelRequest
	13, // 13: omnivoice.localstt.v1.LocalSTT.UnloadModel:input_type -> omnivoice.localstt.v1.UnloadModelRequest
	15, // 14: omnivoice.localstt.v1.LocalSTT.RuntimeInfo:input_type -> omnivoice.localstt.v1.RuntimeInfoRequest
	18, // 15: omnivoice.localstt.v1.LocalSTT.ListModels:input_type -> omnivoice.localstt.v1.ListModelsRequest
	4,  // 16: omnivoice.localstt.v1.LocalSTT.Transcribe:output_type -> omnivoice.localstt.v1.TranscribeResponse
	8,  // 17: omnivoice.localstt.v1.LocalSTT.TranscribeStream:output_type -> omnivoice.localstt.v1.TranscriptEvent
	10, // 18: omnivoice.localstt.v1.LocalSTT.Health:output_type -> omnivoice.localstt.v1.HealthResponse
	12, // 19: omnivoice.localstt.v1.LocalSTT.LoadModel:output_type -> omnivoice.localstt.v1.LoadModelResponse
	14, // 20: omnivoice.localstt.v1.LocalSTT.UnloadModel:output_type -> omnivoice.localstt.v1.UnloadModelResponse
	16, // 21: omnivoice.localstt.v1.LocalSTT.RuntimeInfo:output_type -> omnivoice.localstt.v1.RuntimeInfoResponse
	19, // 22: omnivoice.localstt.v1.LocalSTT.ListModels:output_type -> omnivoice.localstt.v1.ListModelsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_localstt_v1_localstt_proto_init() }
func file_localstt_v1_localstt_proto_init() {
	if File_localstt_v1_localstt_proto != nil {
		return
	}
	file_localstt_v1_localstt_proto_msgTypes[1].OneofWrappers = []any{}
	file_localstt_v1_localstt_proto_msgTypes[6].OneofWrappers = []any{}
	file_localstt_v1_localstt_proto_msgTypes[7].OneofWrappers = []any{}
	file_localstt_v1_localstt_proto_msgTypes[10].OneofWrappers = []any{}
	file_localstt_v1_localstt_proto_msgTypes[11].OneofWrappers = []any{}
	file_localstt_v1_localstt_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localstt_v1_localstt_proto_rawDesc), len(file_localstt_v1_localstt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localstt_v1_localstt_proto_goTypes,
		DependencyIndexes: file_localstt_v1_localstt_proto_depIdxs,
		EnumInfos:         file_localstt_v1_localstt_proto_enumTypes,
		MessageInfos:      file_localstt_v1_localstt_proto_msgTypes,
	}.Build()
	File_localstt_v1_localstt_proto = out.File
	file_localstt_v1_localstt_proto_goTypes = nil
	file_localstt_v1_localstt_proto_depIdxs = nil
}
