// Copyright 2024 PlexusOne. All rights reserved.
// Use of this source code is governed by the MIT license.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: localstt/v1/localstt.proto

package localsttv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalSTT_Transcribe_FullMethodName       = "/omnivoice.localstt.v1.LocalSTT/Transcribe"
	LocalSTT_TranscribeStream_FullMethodName = "/omnivoice.localstt.v1.LocalSTT/TranscribeStream"
	LocalSTT_Health_FullMethodName           = "/omnivoice.localstt.v1.LocalSTT/Health"
	LocalSTT_LoadModel_FullMethodName        = "/omnivoice.localstt.v1.LocalSTT/LoadModel"
	LocalSTT_UnloadModel_FullMethodName      = "/omnivoice.localstt.v1.LocalSTT/UnloadModel"
	LocalSTT_RuntimeInfo_FullMethodName      = "/omnivoice.localstt.v1.LocalSTT/RuntimeInfo"
	LocalSTT_ListModels_FullMethodName       = "/omnivoice.localstt.v1.LocalSTT/ListModels"
)

// LocalSTTClient is the client API for LocalSTT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalSTT service for local STT inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local STT model servers (Whisper MLX, etc.)
// and consumed by Go provider clients in omnivoice-core/providers/whisper-mlx, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalSTTClient interface {
	// Transcribe converts audio to text (batch mode).
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	// TranscribeStream performs streaming transcription.
	// Audio chunks are sent as a stream, transcription results are streamed back.
	TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptEvent], error)
	// Health returns the health status and model information.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// LoadModel loads the STT model into memory.
	// Call this before Transcribe if the model is not auto-loaded.
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error)
	// ListModels returns available models.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type localSTTClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalSTTClient(cc grpc.ClientConnInterface) LocalSTTClient {
	return &localSTTClient{cc}
}

func (c *localSTTClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, LocalSTT_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localSTTClient) TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalSTT_ServiceDesc.Streams[0], LocalSTT_TranscribeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, TranscriptEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalSTT_TranscribeStreamClient = grpc.BidiStreamingClient[AudioChunk, TranscriptEvent]

func (c *localSTTClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LocalSTT_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localSTTClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, LocalSTT_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localSTTClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, LocalSTT_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localSTTClient) RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfoResponse)
	err := c.cc.Invoke(ctx, LocalSTT_RuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localSTTClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, LocalSTT_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalSTTServer is the server API for LocalSTT service.
// All implementations must embed UnimplementedLocalSTTServer
// for forward compatibility.
//
// LocalSTT service for local STT inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local STT model servers (Whisper MLX, etc.)
// and consumed by Go provider clients in omnivoice-core/providers/whisper-mlx, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalSTTServer interface {
	// Transcribe converts audio to text (batch mode).
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	// TranscribeStream performs streaming transcription.
	// Audio chunks are sent as a stream, transcription results are streamed back.
	TranscribeStream(grpc.BidiStreamingServer[AudioChunk, TranscriptEvent]) error
	// Health returns the health status and model information.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// LoadModel loads the STT model into memory.
	// Call this before Transcribe if the model is not auto-loaded.
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error)
	// ListModels returns available models.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedLocalSTTServer()
}

// UnimplementedLocalSTTServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalSTTServer struct{}

func (UnimplementedLocalSTTServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedLocalSTTServer) TranscribeStream(grpc.BidiStreamingServer[AudioChunk, TranscriptEvent]) error {
	return status.Errorf(codes.Unimplemented, "method TranscribeStream not implemented")
}
func (UnimplementedLocalSTTServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLocalSTTServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedLocalSTTServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedLocalSTTServer) RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeInfo not implemented")
}
func (UnimplementedLocalSTTServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLocalSTTServer) mustEmbedUnimplementedLocalSTTServer() {}
func (UnimplementedLocalSTTServer) testEmbeddedByValue()                  {}

// UnsafeLocalSTTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalSTTServer will
// result in compilation errors.
type UnsafeLocalSTTServer interface {
	mustEmbedUnimplementedLocalSTTServer()
}

func RegisterLocalSTTServer(s grpc.ServiceRegistrar, srv LocalSTTServer) {
	// If the following call pancis, it indicates UnimplementedLocalSTTServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalSTT_ServiceDesc, srv)
}

func _LocalSTT_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalSTT_TranscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalSTTServer).TranscribeStream(&grpc.GenericServerStream[AudioChunk, TranscriptEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalSTT_TranscribeStreamServer = grpc.BidiStreamingServer[AudioChunk, TranscriptEvent]

func _LocalSTT_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalSTT_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalSTT_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalSTT_RuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).RuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_RuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).RuntimeInfo(ctx, req.(*RuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalSTT_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalSTTServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalSTT_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalSTTServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalSTT_ServiceDesc is the grpc.ServiceDesc for LocalSTT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalSTT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnivoice.localstt.v1.LocalSTT",
	HandlerType: (*LocalSTTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _LocalSTT_Transcribe_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LocalSTT_Health_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _LocalSTT_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _LocalSTT_UnloadModel_Handler,
		},
		{
			MethodName: "RuntimeInfo",
			Handler:    _LocalSTT_RuntimeInfo_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LocalSTT_ListModels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranscribeStream",
			Handler:       _LocalSTT_TranscribeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "localstt/v1/localstt.proto",
}
