// Copyright 2024 PlexusOne. All rights reserved.
// Use of this source code is governed by the MIT license.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: localtts/v1/localtts.proto

package localttsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalTTS_Synthesize_FullMethodName              = "/omnivoice.localtts.v1.LocalTTS/Synthesize"
	LocalTTS_SynthesizeWithReference_FullMethodName = "/omnivoice.localtts.v1.LocalTTS/SynthesizeWithReference"
	LocalTTS_PrepareVoiceProfile_FullMethodName     = "/omnivoice.localtts.v1.LocalTTS/PrepareVoiceProfile"
	LocalTTS_Health_FullMethodName                  = "/omnivoice.localtts.v1.LocalTTS/Health"
	LocalTTS_LoadModel_FullMethodName               = "/omnivoice.localtts.v1.LocalTTS/LoadModel"
	LocalTTS_UnloadModel_FullMethodName             = "/omnivoice.localtts.v1.LocalTTS/UnloadModel"
	LocalTTS_RuntimeInfo_FullMethodName             = "/omnivoice.localtts.v1.LocalTTS/RuntimeInfo"
)

// LocalTTSClient is the client API for LocalTTS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalTTS service for local TTS inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
// and consumed by Go provider clients in omnivoice-core/providers/f5tts-mlx, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalTTSClient interface {
	// Synthesize converts text to speech, streaming audio chunks as they generate.
	// This enables low-latency playback before synthesis completes.
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	// SynthesizeWithReference performs zero-shot voice cloning using reference audio.
	// The reference audio and transcript are used to clone the voice characteristics.
	SynthesizeWithReference(ctx context.Context, in *ReferenceSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	// PrepareVoiceProfile pre-computes and caches a voice embedding from reference audio.
	// Subsequent synthesis with this profile ID will be faster.
	PrepareVoiceProfile(ctx context.Context, in *PrepareVoiceProfileRequest, opts ...grpc.CallOption) (*PrepareVoiceProfileResponse, error)
	// Health returns the health status and model information.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// LoadModel loads the TTS model into memory.
	// Call this before Synthesize if the model is not auto-loaded.
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error)
}

type localTTSClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalTTSClient(cc grpc.ClientConnInterface) LocalTTSClient {
	return &localTTSClient{cc}
}

func (c *localTTSClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalTTS_ServiceDesc.Streams[0], LocalTTS_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalTTS_SynthesizeClient = grpc.ServerStreamingClient[AudioChunk]

func (c *localTTSClient) SynthesizeWithReference(ctx context.Context, in *ReferenceSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalTTS_ServiceDesc.Streams[1], LocalTTS_SynthesizeWithReference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReferenceSynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalTTS_SynthesizeWithReferenceClient = grpc.ServerStreamingClient[AudioChunk]

func (c *localTTSClient) PrepareVoiceProfile(ctx context.Context, in *PrepareVoiceProfileRequest, opts ...grpc.CallOption) (*PrepareVoiceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareVoiceProfileResponse)
	err := c.cc.Invoke(ctx, LocalTTS_PrepareVoiceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localTTSClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LocalTTS_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localTTSClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, LocalTTS_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localTTSClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, LocalTTS_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localTTSClient) RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfoResponse)
	err := c.cc.Invoke(ctx, LocalTTS_RuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalTTSServer is the server API for LocalTTS service.
// All implementations must embed UnimplementedLocalTTSServer
// for forward compatibility.
//
// LocalTTS service for local TTS inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
// and consumed by Go provider clients in omnivoice-core/providers/f5tts-mlx, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalTTSServer interface {
	// Synthesize converts text to speech, streaming audio chunks as they generate.
	// This enables low-latency playback before synthesis completes.
	Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	// SynthesizeWithReference performs zero-shot voice cloning using reference audio.
	// The reference audio and transcript are used to clone the voice characteristics.
	SynthesizeWithReference(*ReferenceSynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	// PrepareVoiceProfile pre-computes and caches a voice embedding from reference audio.
	// Subsequent synthesis with this profile ID will be faster.
	PrepareVoiceProfile(context.Context, *PrepareVoiceProfileRequest) (*PrepareVoiceProfileResponse, error)
	// Health returns the health status and model information.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// LoadModel loads the TTS model into memory.
	// Call this before Synthesize if the model is not auto-loaded.
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error)
	mustEmbedUnimplementedLocalTTSServer()
}

// UnimplementedLocalTTSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalTTSServer struct{}

func (UnimplementedLocalTTSServer) Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedLocalTTSServer) SynthesizeWithReference(*ReferenceSynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeWithReference not implemented")
}
func (UnimplementedLocalTTSServer) PrepareVoiceProfile(context.Context, *PrepareVoiceProfileRequest) (*PrepareVoiceProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareVoiceProfile not implemented")
}
func (UnimplementedLocalTTSServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLocalTTSServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedLocalTTSServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedLocalTTSServer) RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeInfo not implemented")
}
func (UnimplementedLocalTTSServer) mustEmbedUnimplementedLocalTTSServer() {}
func (UnimplementedLocalTTSServer) testEmbeddedByValue()                  {}

// UnsafeLocalTTSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalTTSServer will
// result in compilation errors.
type UnsafeLocalTTSServer interface {
	mustEmbedUnimplementedLocalTTSServer()
}

func RegisterLocalTTSServer(s grpc.ServiceRegistrar, srv LocalTTSServer) {
	// If the following call pancis, it indicates UnimplementedLocalTTSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalTTS_ServiceDesc, srv)
}

func _LocalTTS_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalTTSServer).Synthesize(m, &grpc.GenericServerStream[SynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalTTS_SynthesizeServer = grpc.ServerStreamingServer[AudioChunk]

func _LocalTTS_SynthesizeWithReference_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReferenceSynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalTTSServer).SynthesizeWithReference(m, &grpc.GenericServerStream[ReferenceSynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalTTS_SynthesizeWithReferenceServer = grpc.ServerStreamingServer[AudioChunk]

func _LocalTTS_PrepareVoiceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareVoiceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalTTSServer).PrepareVoiceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalTTS_PrepareVoiceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalTTSServer).PrepareVoiceProfile(ctx, req.(*PrepareVoiceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalTTS_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalTTSServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalTTS_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalTTSServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalTTS_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalTTSServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalTTS_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalTTSServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalTTS_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalTTSServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalTTS_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalTTSServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalTTS_RuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalTTSServer).RuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalTTS_RuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalTTSServer).RuntimeInfo(ctx, req.(*RuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalTTS_ServiceDesc is the grpc.ServiceDesc for LocalTTS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalTTS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnivoice.localtts.v1.LocalTTS",
	HandlerType: (*LocalTTSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareVoiceProfile",
			Handler:    _LocalTTS_PrepareVoiceProfile_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LocalTTS_Health_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _LocalTTS_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _LocalTTS_UnloadModel_Handler,
		},
		{
			MethodName: "RuntimeInfo",
			Handler:    _LocalTTS_RuntimeInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _LocalTTS_Synthesize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeWithReference",
			Handler:       _LocalTTS_SynthesizeWithReference_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "localtts/v1/localtts.proto",
}
