// Copyright 2024 PlexusOne. All rights reserved.
// Use of this source code is governed by the MIT license.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: localvoice/v1/localvoice.proto

package localvoicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalVoice_Synthesize_FullMethodName              = "/omnivoice.localvoice.v1.LocalVoice/Synthesize"
	LocalVoice_SynthesizeWithReference_FullMethodName = "/omnivoice.localvoice.v1.LocalVoice/SynthesizeWithReference"
	LocalVoice_PrepareVoiceProfile_FullMethodName     = "/omnivoice.localvoice.v1.LocalVoice/PrepareVoiceProfile"
	LocalVoice_Health_FullMethodName                  = "/omnivoice.localvoice.v1.LocalVoice/Health"
	LocalVoice_LoadModel_FullMethodName               = "/omnivoice.localvoice.v1.LocalVoice/LoadModel"
	LocalVoice_UnloadModel_FullMethodName             = "/omnivoice.localvoice.v1.LocalVoice/UnloadModel"
	LocalVoice_RuntimeInfo_FullMethodName             = "/omnivoice.localvoice.v1.LocalVoice/RuntimeInfo"
)

// LocalVoiceClient is the client API for LocalVoice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalVoice service for local TTS inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
// and consumed by Go provider clients in omni-f5tts, omni-qwen, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalVoiceClient interface {
	// Synthesize converts text to speech, streaming audio chunks as they generate.
	// This enables low-latency playback before synthesis completes.
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	// SynthesizeWithReference performs zero-shot voice cloning using reference audio.
	// The reference audio and transcript are used to clone the voice characteristics.
	SynthesizeWithReference(ctx context.Context, in *ReferenceSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	// PrepareVoiceProfile pre-computes and caches a voice embedding from reference audio.
	// Subsequent synthesis with this profile ID will be faster.
	PrepareVoiceProfile(ctx context.Context, in *PrepareVoiceProfileRequest, opts ...grpc.CallOption) (*PrepareVoiceProfileResponse, error)
	// Health returns the health status and model information.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// LoadModel loads the TTS model into memory.
	// Call this before Synthesize if the model is not auto-loaded.
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error)
}

type localVoiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalVoiceClient(cc grpc.ClientConnInterface) LocalVoiceClient {
	return &localVoiceClient{cc}
}

func (c *localVoiceClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalVoice_ServiceDesc.Streams[0], LocalVoice_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalVoice_SynthesizeClient = grpc.ServerStreamingClient[AudioChunk]

func (c *localVoiceClient) SynthesizeWithReference(ctx context.Context, in *ReferenceSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalVoice_ServiceDesc.Streams[1], LocalVoice_SynthesizeWithReference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReferenceSynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalVoice_SynthesizeWithReferenceClient = grpc.ServerStreamingClient[AudioChunk]

func (c *localVoiceClient) PrepareVoiceProfile(ctx context.Context, in *PrepareVoiceProfileRequest, opts ...grpc.CallOption) (*PrepareVoiceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareVoiceProfileResponse)
	err := c.cc.Invoke(ctx, LocalVoice_PrepareVoiceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localVoiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LocalVoice_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localVoiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, LocalVoice_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localVoiceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, LocalVoice_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localVoiceClient) RuntimeInfo(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfoResponse)
	err := c.cc.Invoke(ctx, LocalVoice_RuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalVoiceServer is the server API for LocalVoice service.
// All implementations must embed UnimplementedLocalVoiceServer
// for forward compatibility.
//
// LocalVoice service for local TTS inference via gRPC over Unix Domain Socket.
//
// This service is implemented by local TTS model servers (F5-TTS MLX, Qwen3-TTS, etc.)
// and consumed by Go provider clients in omni-f5tts, omni-qwen, etc.
//
// Connection: unix:///tmp/omnivoice-{provider}.sock
type LocalVoiceServer interface {
	// Synthesize converts text to speech, streaming audio chunks as they generate.
	// This enables low-latency playback before synthesis completes.
	Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	// SynthesizeWithReference performs zero-shot voice cloning using reference audio.
	// The reference audio and transcript are used to clone the voice characteristics.
	SynthesizeWithReference(*ReferenceSynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	// PrepareVoiceProfile pre-computes and caches a voice embedding from reference audio.
	// Subsequent synthesis with this profile ID will be faster.
	PrepareVoiceProfile(context.Context, *PrepareVoiceProfileRequest) (*PrepareVoiceProfileResponse, error)
	// Health returns the health status and model information.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// LoadModel loads the TTS model into memory.
	// Call this before Synthesize if the model is not auto-loaded.
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// UnloadModel unloads the model from memory to free resources.
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// RuntimeInfo returns information about the runtime environment.
	RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error)
	mustEmbedUnimplementedLocalVoiceServer()
}

// UnimplementedLocalVoiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalVoiceServer struct{}

func (UnimplementedLocalVoiceServer) Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedLocalVoiceServer) SynthesizeWithReference(*ReferenceSynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeWithReference not implemented")
}
func (UnimplementedLocalVoiceServer) PrepareVoiceProfile(context.Context, *PrepareVoiceProfileRequest) (*PrepareVoiceProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareVoiceProfile not implemented")
}
func (UnimplementedLocalVoiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLocalVoiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedLocalVoiceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedLocalVoiceServer) RuntimeInfo(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeInfo not implemented")
}
func (UnimplementedLocalVoiceServer) mustEmbedUnimplementedLocalVoiceServer() {}
func (UnimplementedLocalVoiceServer) testEmbeddedByValue()                    {}

// UnsafeLocalVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalVoiceServer will
// result in compilation errors.
type UnsafeLocalVoiceServer interface {
	mustEmbedUnimplementedLocalVoiceServer()
}

func RegisterLocalVoiceServer(s grpc.ServiceRegistrar, srv LocalVoiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalVoiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalVoice_ServiceDesc, srv)
}

func _LocalVoice_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalVoiceServer).Synthesize(m, &grpc.GenericServerStream[SynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalVoice_SynthesizeServer = grpc.ServerStreamingServer[AudioChunk]

func _LocalVoice_SynthesizeWithReference_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReferenceSynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalVoiceServer).SynthesizeWithReference(m, &grpc.GenericServerStream[ReferenceSynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalVoice_SynthesizeWithReferenceServer = grpc.ServerStreamingServer[AudioChunk]

func _LocalVoice_PrepareVoiceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareVoiceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalVoiceServer).PrepareVoiceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalVoice_PrepareVoiceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalVoiceServer).PrepareVoiceProfile(ctx, req.(*PrepareVoiceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalVoice_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalVoiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalVoice_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalVoiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalVoice_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalVoiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalVoice_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalVoiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalVoice_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalVoiceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalVoice_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalVoiceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalVoice_RuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalVoiceServer).RuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalVoice_RuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalVoiceServer).RuntimeInfo(ctx, req.(*RuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalVoice_ServiceDesc is the grpc.ServiceDesc for LocalVoice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalVoice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnivoice.localvoice.v1.LocalVoice",
	HandlerType: (*LocalVoiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareVoiceProfile",
			Handler:    _LocalVoice_PrepareVoiceProfile_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LocalVoice_Health_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _LocalVoice_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _LocalVoice_UnloadModel_Handler,
		},
		{
			MethodName: "RuntimeInfo",
			Handler:    _LocalVoice_RuntimeInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _LocalVoice_Synthesize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeWithReference",
			Handler:       _LocalVoice_SynthesizeWithReference_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "localvoice/v1/localvoice.proto",
}
