// Copyright 2024 PlexusOne. All rights reserved.
// Use of this source code is governed by the MIT license.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: localvoice/v1/localvoice.proto

package localvoicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioFormat specifies the audio encoding format.
type AudioFormat int32

const (
	// AUDIO_FORMAT_UNSPECIFIED indicates no format preference.
	AudioFormat_AUDIO_FORMAT_UNSPECIFIED AudioFormat = 0
	// AUDIO_FORMAT_WAV is WAV format with headers.
	AudioFormat_AUDIO_FORMAT_WAV AudioFormat = 1
	// AUDIO_FORMAT_PCM_S16LE is raw PCM, signed 16-bit little-endian.
	AudioFormat_AUDIO_FORMAT_PCM_S16LE AudioFormat = 2
	// AUDIO_FORMAT_PCM_F32LE is raw PCM, float32 little-endian.
	AudioFormat_AUDIO_FORMAT_PCM_F32LE AudioFormat = 3
	// AUDIO_FORMAT_MP3 is MP3 format.
	AudioFormat_AUDIO_FORMAT_MP3 AudioFormat = 4
	// AUDIO_FORMAT_MULAW_8K is G.711 mu-law at 8kHz for telephony.
	AudioFormat_AUDIO_FORMAT_MULAW_8K AudioFormat = 5
	// AUDIO_FORMAT_OPUS is Opus format.
	AudioFormat_AUDIO_FORMAT_OPUS AudioFormat = 6
)

// Enum value maps for AudioFormat.
var (
	AudioFormat_name = map[int32]string{
		0: "AUDIO_FORMAT_UNSPECIFIED",
		1: "AUDIO_FORMAT_WAV",
		2: "AUDIO_FORMAT_PCM_S16LE",
		3: "AUDIO_FORMAT_PCM_F32LE",
		4: "AUDIO_FORMAT_MP3",
		5: "AUDIO_FORMAT_MULAW_8K",
		6: "AUDIO_FORMAT_OPUS",
	}
	AudioFormat_value = map[string]int32{
		"AUDIO_FORMAT_UNSPECIFIED": 0,
		"AUDIO_FORMAT_WAV":         1,
		"AUDIO_FORMAT_PCM_S16LE":   2,
		"AUDIO_FORMAT_PCM_F32LE":   3,
		"AUDIO_FORMAT_MP3":         4,
		"AUDIO_FORMAT_MULAW_8K":    5,
		"AUDIO_FORMAT_OPUS":        6,
	}
)

func (x AudioFormat) Enum() *AudioFormat {
	p := new(AudioFormat)
	*p = x
	return p
}

func (x AudioFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_localvoice_v1_localvoice_proto_enumTypes[0].Descriptor()
}

func (AudioFormat) Type() protoreflect.EnumType {
	return &file_localvoice_v1_localvoice_proto_enumTypes[0]
}

func (x AudioFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat.Descriptor instead.
func (AudioFormat) EnumDescriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{0}
}

// SynthesizeRequest is a request to synthesize speech from text.
type SynthesizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the text to synthesize.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// voice_id is the voice profile ID or "default" for the default voice.
	VoiceId string `protobuf:"bytes,2,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	// format is the desired audio output format.
	Format AudioFormat `protobuf:"varint,3,opt,name=format,proto3,enum=omnivoice.localvoice.v1.AudioFormat" json:"format,omitempty"`
	// speed is the speech rate multiplier (default 1.0).
	// Values > 1.0 speed up, values < 1.0 slow down.
	Speed *float32 `protobuf:"fixed32,4,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	// language is the BCP-47 language code (e.g., "en-US", "zh-CN").
	// If not specified, auto-detection may be used.
	Language      *string `protobuf:"bytes,5,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *SynthesizeRequest) GetFormat() AudioFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_AUDIO_FORMAT_UNSPECIFIED
}

func (x *SynthesizeRequest) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *SynthesizeRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// ReferenceSynthesizeRequest is a request for zero-shot voice cloning.
type ReferenceSynthesizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the text to synthesize in the cloned voice.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// reference_audio is the WAV/PCM audio bytes of the reference speaker.
	// Recommended: 5-15 seconds of clear speech.
	ReferenceAudio []byte `protobuf:"bytes,2,opt,name=reference_audio,json=referenceAudio,proto3" json:"reference_audio,omitempty"`
	// reference_text is the transcript of the reference audio.
	// Must accurately match what is spoken in reference_audio.
	ReferenceText string `protobuf:"bytes,3,opt,name=reference_text,json=referenceText,proto3" json:"reference_text,omitempty"`
	// format is the desired audio output format.
	Format AudioFormat `protobuf:"varint,4,opt,name=format,proto3,enum=omnivoice.localvoice.v1.AudioFormat" json:"format,omitempty"`
	// speed is the speech rate multiplier (default 1.0).
	Speed *float32 `protobuf:"fixed32,5,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	// language is the BCP-47 language code.
	Language      *string `protobuf:"bytes,6,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceSynthesizeRequest) Reset() {
	*x = ReferenceSynthesizeRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceSynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceSynthesizeRequest) ProtoMessage() {}

func (x *ReferenceSynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceSynthesizeRequest.ProtoReflect.Descriptor instead.
func (*ReferenceSynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{1}
}

func (x *ReferenceSynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReferenceSynthesizeRequest) GetReferenceAudio() []byte {
	if x != nil {
		return x.ReferenceAudio
	}
	return nil
}

func (x *ReferenceSynthesizeRequest) GetReferenceText() string {
	if x != nil {
		return x.ReferenceText
	}
	return ""
}

func (x *ReferenceSynthesizeRequest) GetFormat() AudioFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_AUDIO_FORMAT_UNSPECIFIED
}

func (x *ReferenceSynthesizeRequest) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *ReferenceSynthesizeRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// AudioChunk represents a chunk of streaming audio output.
type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains raw audio bytes for this chunk.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// is_final is true for the last chunk in the stream.
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// metadata is included only on the first chunk.
	Metadata      *AudioMetadata `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *AudioChunk) GetMetadata() *AudioMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AudioMetadata describes the audio format of the stream.
type AudioMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// format is the audio format.
	Format AudioFormat `protobuf:"varint,1,opt,name=format,proto3,enum=omnivoice.localvoice.v1.AudioFormat" json:"format,omitempty"`
	// sample_rate is the sample rate in Hz (e.g., 24000, 44100).
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// channels is the number of audio channels (1 = mono, 2 = stereo).
	Channels int32 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	// bit_depth is the bits per sample (e.g., 16, 32).
	BitDepth      int32 `protobuf:"varint,4,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMetadata) Reset() {
	*x = AudioMetadata{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMetadata) ProtoMessage() {}

func (x *AudioMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMetadata.ProtoReflect.Descriptor instead.
func (*AudioMetadata) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{3}
}

func (x *AudioMetadata) GetFormat() AudioFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_AUDIO_FORMAT_UNSPECIFIED
}

func (x *AudioMetadata) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioMetadata) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioMetadata) GetBitDepth() int32 {
	if x != nil {
		return x.BitDepth
	}
	return 0
}

// PrepareVoiceProfileRequest requests pre-computation of a voice embedding.
type PrepareVoiceProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile_id is the unique identifier for this voice profile.
	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// reference_audio is the WAV/PCM audio bytes of the reference speaker.
	ReferenceAudio []byte `protobuf:"bytes,2,opt,name=reference_audio,json=referenceAudio,proto3" json:"reference_audio,omitempty"`
	// reference_text is the transcript of the reference audio.
	ReferenceText string `protobuf:"bytes,3,opt,name=reference_text,json=referenceText,proto3" json:"reference_text,omitempty"`
	// language is the BCP-47 language code.
	Language      *string `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareVoiceProfileRequest) Reset() {
	*x = PrepareVoiceProfileRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareVoiceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareVoiceProfileRequest) ProtoMessage() {}

func (x *PrepareVoiceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareVoiceProfileRequest.ProtoReflect.Descriptor instead.
func (*PrepareVoiceProfileRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareVoiceProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *PrepareVoiceProfileRequest) GetReferenceAudio() []byte {
	if x != nil {
		return x.ReferenceAudio
	}
	return nil
}

func (x *PrepareVoiceProfileRequest) GetReferenceText() string {
	if x != nil {
		return x.ReferenceText
	}
	return ""
}

func (x *PrepareVoiceProfileRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// PrepareVoiceProfileResponse contains the result of profile preparation.
type PrepareVoiceProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile_id is the profile identifier that was prepared.
	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// cached indicates whether the embedding was successfully cached.
	Cached bool `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	// embedding_size_bytes is the size of the cached embedding.
	EmbeddingSizeBytes int64 `protobuf:"varint,3,opt,name=embedding_size_bytes,json=embeddingSizeBytes,proto3" json:"embedding_size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepareVoiceProfileResponse) Reset() {
	*x = PrepareVoiceProfileResponse{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareVoiceProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareVoiceProfileResponse) ProtoMessage() {}

func (x *PrepareVoiceProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareVoiceProfileResponse.ProtoReflect.Descriptor instead.
func (*PrepareVoiceProfileResponse) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareVoiceProfileResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *PrepareVoiceProfileResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *PrepareVoiceProfileResponse) GetEmbeddingSizeBytes() int64 {
	if x != nil {
		return x.EmbeddingSizeBytes
	}
	return 0
}

// HealthRequest is an empty request for health checking.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{6}
}

// HealthResponse contains health and model status information.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy indicates whether the service is operational.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// model_loaded indicates whether the TTS model is loaded in memory.
	ModelLoaded bool `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	// model_name is the name of the loaded model (e.g., "f5-tts-mlx").
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// model_version is the version of the loaded model.
	ModelVersion string `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// available_voices lists the prepared voice profile IDs.
	AvailableVoices []string `protobuf:"bytes,5,rep,name=available_voices,json=availableVoices,proto3" json:"available_voices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetAvailableVoices() []string {
	if x != nil {
		return x.AvailableVoices
	}
	return nil
}

// LoadModelRequest requests loading the TTS model into memory.
type LoadModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model_path optionally overrides the default model path.
	ModelPath     *string `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3,oneof" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{8}
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil && x.ModelPath != nil {
		return *x.ModelPath
	}
	return ""
}

// LoadModelResponse contains the result of model loading.
type LoadModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the model was loaded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// load_time_ms is the time taken to load the model in milliseconds.
	LoadTimeMs int64 `protobuf:"varint,2,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	// memory_used_mb is the memory consumed by the loaded model.
	MemoryUsedMb int64 `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	// error_message contains error details if success is false.
	ErrorMessage  *string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{9}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetLoadTimeMs() int64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

func (x *LoadModelResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *LoadModelResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// UnloadModelRequest requests unloading the TTS model from memory.
type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{10}
}

// UnloadModelResponse contains the result of model unloading.
type UnloadModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the model was unloaded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// memory_freed_mb is the memory freed by unloading.
	MemoryFreedMb int64 `protobuf:"varint,2,opt,name=memory_freed_mb,json=memoryFreedMb,proto3" json:"memory_freed_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{11}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadModelResponse) GetMemoryFreedMb() int64 {
	if x != nil {
		return x.MemoryFreedMb
	}
	return 0
}

// RuntimeInfoRequest requests runtime environment information.
type RuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoRequest) Reset() {
	*x = RuntimeInfoRequest{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoRequest) ProtoMessage() {}

func (x *RuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*RuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{12}
}

// RuntimeInfoResponse contains runtime environment details.
type RuntimeInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_type is the compute device ("mlx", "mps", "cpu", "cuda").
	DeviceType string `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// memory_used_mb is the current memory usage in MB.
	MemoryUsedMb int64 `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	// memory_available_mb is the available memory in MB.
	MemoryAvailableMb int64 `protobuf:"varint,3,opt,name=memory_available_mb,json=memoryAvailableMb,proto3" json:"memory_available_mb,omitempty"`
	// framework_version is the ML framework version (e.g., MLX version).
	FrameworkVersion string `protobuf:"bytes,4,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	// python_version is the Python version if applicable.
	PythonVersion string `protobuf:"bytes,5,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	// model_info contains information about the loaded model.
	ModelInfo     *ModelInfo `protobuf:"bytes,6,opt,name=model_info,json=modelInfo,proto3,oneof" json:"model_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoResponse) Reset() {
	*x = RuntimeInfoResponse{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoResponse) ProtoMessage() {}

func (x *RuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*RuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{13}
}

func (x *RuntimeInfoResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *RuntimeInfoResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *RuntimeInfoResponse) GetMemoryAvailableMb() int64 {
	if x != nil {
		return x.MemoryAvailableMb
	}
	return 0
}

func (x *RuntimeInfoResponse) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *RuntimeInfoResponse) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *RuntimeInfoResponse) GetModelInfo() *ModelInfo {
	if x != nil {
		return x.ModelInfo
	}
	return nil
}

// ModelInfo contains details about the loaded model.
type ModelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the model name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the model version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// parameter_count is the number of model parameters.
	ParameterCount int64 `protobuf:"varint,3,opt,name=parameter_count,json=parameterCount,proto3" json:"parameter_count,omitempty"`
	// supported_languages lists the supported language codes.
	SupportedLanguages []string `protobuf:"bytes,4,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_localvoice_v1_localvoice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_localvoice_v1_localvoice_proto_rawDescGZIP(), []int{14}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfo) GetParameterCount() int64 {
	if x != nil {
		return x.ParameterCount
	}
	return 0
}

func (x *ModelInfo) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

var File_localvoice_v1_localvoice_proto protoreflect.FileDescriptor

const file_localvoice_v1_localvoice_proto_rawDesc = "" +
	"\n" +
	"\x1elocalvoice/v1/localvoice.proto\x12\x17omnivoice.localvoice.v1\"\xd3\x01\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bvoice_id\x18\x02 \x01(\tR\avoiceId\x12<\n" +
	"\x06format\x18\x03 \x01(\x0e2$.omnivoice.localvoice.v1.AudioFormatR\x06format\x12\x19\n" +
	"\x05speed\x18\x04 \x01(\x02H\x00R\x05speed\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x05 \x01(\tH\x01R\blanguage\x88\x01\x01B\b\n" +
	"\x06_speedB\v\n" +
	"\t_language\"\x91\x02\n" +
	"\x1aReferenceSynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0freference_audio\x18\x02 \x01(\fR\x0ereferenceAudio\x12%\n" +
	"\x0ereference_text\x18\x03 \x01(\tR\rreferenceText\x12<\n" +
	"\x06format\x18\x04 \x01(\x0e2$.omnivoice.localvoice.v1.AudioFormatR\x06format\x12\x19\n" +
	"\x05speed\x18\x05 \x01(\x02H\x00R\x05speed\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x06 \x01(\tH\x01R\blanguage\x88\x01\x01B\b\n" +
	"\x06_speedB\v\n" +
	"\t_language\"\x91\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12G\n" +
	"\bmetadata\x18\x03 \x01(\v2&.omnivoice.localvoice.v1.AudioMetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\xa7\x01\n" +
	"\rAudioMetadata\x12<\n" +
	"\x06format\x18\x01 \x01(\x0e2$.omnivoice.localvoice.v1.AudioFormatR\x06format\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12\x1b\n" +
	"\tbit_depth\x18\x04 \x01(\x05R\bbitDepth\"\xb9\x01\n" +
	"\x1aPrepareVoiceProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12'\n" +
	"\x0freference_audio\x18\x02 \x01(\fR\x0ereferenceAudio\x12%\n" +
	"\x0ereference_text\x18\x03 \x01(\tR\rreferenceText\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\"\x86\x01\n" +
	"\x1bPrepareVoiceProfileResponse\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached\x120\n" +
	"\x14embedding_size_bytes\x18\x03 \x01(\x03R\x12embeddingSizeBytes\"\x0f\n" +
	"\rHealthRequest\"\xbc\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12)\n" +
	"\x10available_voices\x18\x05 \x03(\tR\x0favailableVoices\"E\n" +
	"\x10LoadModelRequest\x12\"\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tH\x00R\tmodelPath\x88\x01\x01B\r\n" +
	"\v_model_path\"\xb1\x01\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\fload_time_ms\x18\x02 \x01(\x03R\n" +
	"loadTimeMs\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x03R\fmemoryUsedMb\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\x14\n" +
	"\x12UnloadModelRequest\"W\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fmemory_freed_mb\x18\x02 \x01(\x03R\rmemoryFreedMb\"\x14\n" +
	"\x12RuntimeInfoRequest\"\xb7\x02\n" +
	"\x13RuntimeInfoResponse\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12.\n" +
	"\x13memory_available_mb\x18\x03 \x01(\x03R\x11memoryAvailableMb\x12+\n" +
	"\x11framework_version\x18\x04 \x01(\tR\x10frameworkVersion\x12%\n" +
	"\x0epython_version\x18\x05 \x01(\tR\rpythonVersion\x12F\n" +
	"\n" +
	"model_info\x18\x06 \x01(\v2\".omnivoice.localvoice.v1.ModelInfoH\x00R\tmodelInfo\x88\x01\x01B\r\n" +
	"\v_model_info\"\x93\x01\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fparameter_count\x18\x03 \x01(\x03R\x0eparameterCount\x12/\n" +
	"\x13supported_languages\x18\x04 \x03(\tR\x12supportedLanguages*\xc1\x01\n" +
	"\vAudioFormat\x12\x1c\n" +
	"\x18AUDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AUDIO_FORMAT_WAV\x10\x01\x12\x1a\n" +
	"\x16AUDIO_FORMAT_PCM_S16LE\x10\x02\x12\x1a\n" +
	"\x16AUDIO_FORMAT_PCM_F32LE\x10\x03\x12\x14\n" +
	"\x10AUDIO_FORMAT_MP3\x10\x04\x12\x19\n" +
	"\x15AUDIO_FORMAT_MULAW_8K\x10\x05\x12\x15\n" +
	"\x11AUDIO_FORMAT_OPUS\x10\x062\xfa\x05\n" +
	"\n" +
	"LocalVoice\x12_\n" +
	"\n" +
	"Synthesize\x12*.omnivoice.localvoice.v1.SynthesizeRequest\x1a#.omnivoice.localvoice.v1.AudioChunk0\x01\x12u\n" +
	"\x17SynthesizeWithReference\x123.omnivoice.localvoice.v1.ReferenceSynthesizeRequest\x1a#.omnivoice.localvoice.v1.AudioChunk0\x01\x12\x80\x01\n" +
	"\x13PrepareVoiceProfile\x123.omnivoice.localvoice.v1.PrepareVoiceProfileRequest\x1a4.omnivoice.localvoice.v1.PrepareVoiceProfileResponse\x12Y\n" +
	"\x06Health\x12&.omnivoice.localvoice.v1.HealthRequest\x1a'.omnivoice.localvoice.v1.HealthResponse\x12b\n" +
	"\tLoadModel\x12).omnivoice.localvoice.v1.LoadModelRequest\x1a*.omnivoice.localvoice.v1.LoadModelResponse\x12h\n" +
	"\vUnloadModel\x12+.omnivoice.localvoice.v1.UnloadModelRequest\x1a,.omnivoice.localvoice.v1.UnloadModelResponse\x12h\n" +
	"\vRuntimeInfo\x12+.omnivoice.localvoice.v1.RuntimeInfoRequest\x1a,.omnivoice.localvoice.v1.RuntimeInfoResponseBFZDgithub.com/plexusone/omnivoice-core/proto/localvoice/v1;localvoicev1b\x06proto3"

var (
	file_localvoice_v1_localvoice_proto_rawDescOnce sync.Once
	file_localvoice_v1_localvoice_proto_rawDescData []byte
)

func file_localvoice_v1_localvoice_proto_rawDescGZIP() []byte {
	file_localvoice_v1_localvoice_proto_rawDescOnce.Do(func() {
		file_localvoice_v1_localvoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localvoice_v1_localvoice_proto_rawDesc), len(file_localvoice_v1_localvoice_proto_rawDesc)))
	})
	return file_localvoice_v1_localvoice_proto_rawDescData
}

var file_localvoice_v1_localvoice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_localvoice_v1_localvoice_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_localvoice_v1_localvoice_proto_goTypes = []any{
	(AudioFormat)(0),                    // 0: omnivoice.localvoice.v1.AudioFormat
	(*SynthesizeRequest)(nil),           // 1: omnivoice.localvoice.v1.SynthesizeRequest
	(*ReferenceSynthesizeRequest)(nil),  // 2: omnivoice.localvoice.v1.ReferenceSynthesizeRequest
	(*AudioChunk)(nil),                  // 3: omnivoice.localvoice.v1.AudioChunk
	(*AudioMetadata)(nil),               // 4: omnivoice.localvoice.v1.AudioMetadata
	(*PrepareVoiceProfileRequest)(nil),  // 5: omnivoice.localvoice.v1.PrepareVoiceProfileRequest
	(*PrepareVoiceProfileResponse)(nil), // 6: omnivoice.localvoice.v1.PrepareVoiceProfileResponse
	(*HealthRequest)(nil),               // 7: omnivoice.localvoice.v1.HealthRequest
	(*HealthResponse)(nil),              // 8: omnivoice.localvoice.v1.HealthResponse
	(*LoadModelRequest)(nil),            // 9: omnivoice.localvoice.v1.LoadModelRequest
	(*LoadModelResponse)(nil),           // 10: omnivoice.localvoice.v1.LoadModelResponse
	(*UnloadModelRequest)(nil),          // 11: omnivoice.localvoice.v1.UnloadModelRequest
	(*UnloadModelResponse)(nil),         // 12: omnivoice.localvoice.v1.UnloadModelResponse
	(*RuntimeInfoRequest)(nil),          // 13: omnivoice.localvoice.v1.RuntimeInfoRequest
	(*RuntimeInfoResponse)(nil),         // 14: omnivoice.localvoice.v1.RuntimeInfoResponse
	(*ModelInfo)(nil),                   // 15: omnivoice.localvoice.v1.ModelInfo
}
var file_localvoice_v1_localvoice_proto_depIdxs = []int32{
	0,  // 0: omnivoice.localvoice.v1.SynthesizeRequest.format:type_name -> omnivoice.localvoice.v1.AudioFormat
	0,  // 1: omnivoice.localvoice.v1.ReferenceSynthesizeRequest.format:type_name -> omnivoice.localvoice.v1.AudioFormat
	4,  // 2: omnivoice.localvoice.v1.AudioChunk.metadata:type_name -> omnivoice.localvoice.v1.AudioMetadata
	0,  // 3: omnivoice.localvoice.v1.AudioMetadata.format:type_name -> omnivoice.localvoice.v1.AudioFormat
	15, // 4: omnivoice.localvoice.v1.RuntimeInfoResponse.model_info:type_name -> omnivoice.localvoice.v1.ModelInfo
	1,  // 5: omnivoice.localvoice.v1.LocalVoice.Synthesize:input_type -> omnivoice.localvoice.v1.SynthesizeRequest
	2,  // 6: omnivoice.localvoice.v1.LocalVoice.SynthesizeWithReference:input_type -> omnivoice.localvoice.v1.ReferenceSynthesizeRequest
	5,  // 7: omnivoice.localvoice.v1.LocalVoice.PrepareVoiceProfile:input_type -> omnivoice.localvoice.v1.PrepareVoiceProfileRequest
	7,  // 8: omnivoice.localvoice.v1.LocalVoice.Health:input_type -> omnivoice.localvoice.v1.HealthRequest
	9,  // 9: omnivoice.localvoice.v1.LocalVoice.LoadModel:input_type -> omnivoice.localvoice.v1.LoadModelRequest
	11, // 10: omnivoice.localvoice.v1.LocalVoice.UnloadModel:input_type -> omnivoice.localvoice.v1.UnloadModelRequest
	13, // 11: omnivoice.localvoice.v1.LocalVoice.RuntimeInfo:input_type -> omnivoice.localvoice.v1.RuntimeInfoRequest
	3,  // 12: omnivoice.localvoice.v1.LocalVoice.Synthesize:output_type -> omnivoice.localvoice.v1.AudioChunk
	3,  // 13: omnivoice.localvoice.v1.LocalVoice.SynthesizeWithReference:output_type -> omnivoice.localvoice.v1.AudioChunk
	6,  // 14: omnivoice.localvoice.v1.LocalVoice.PrepareVoiceProfile:output_type -> omnivoice.localvoice.v1.PrepareVoiceProfileResponse
	8,  // 15: omnivoice.localvoice.v1.LocalVoice.Health:output_type -> omnivoice.localvoice.v1.HealthResponse
	10, // 16: omnivoice.localvoice.v1.LocalVoice.LoadModel:output_type -> omnivoice.localvoice.v1.LoadModelResponse
	12, // 17: omnivoice.localvoice.v1.LocalVoice.UnloadModel:output_type -> omnivoice.localvoice.v1.UnloadModelResponse
	14, // 18: omnivoice.localvoice.v1.LocalVoice.RuntimeInfo:output_type -> omnivoice.localvoice.v1.RuntimeInfoResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_localvoice_v1_localvoice_proto_init() }
func file_localvoice_v1_localvoice_proto_init() {
	if File_localvoice_v1_localvoice_proto != nil {
		return
	}
	file_localvoice_v1_localvoice_proto_msgTypes[0].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[1].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[2].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[4].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[8].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[9].OneofWrappers = []any{}
	file_localvoice_v1_localvoice_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localvoice_v1_localvoice_proto_rawDesc), len(file_localvoice_v1_localvoice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localvoice_v1_localvoice_proto_goTypes,
		DependencyIndexes: file_localvoice_v1_localvoice_proto_depIdxs,
		EnumInfos:         file_localvoice_v1_localvoice_proto_enumTypes,
		MessageInfos:      file_localvoice_v1_localvoice_proto_msgTypes,
	}.Build()
	File_localvoice_v1_localvoice_proto = out.File
	file_localvoice_v1_localvoice_proto_goTypes = nil
	file_localvoice_v1_localvoice_proto_depIdxs = nil
}
